image: Ubuntu

services:
- docker

before_build:
- sh: |
    echo "Pulling Azure Cosmos Emulator Docker image for Linux ..."
    bash ./pull-docker-azure-cosmos-emulator-linux.sh

    echo "Running Azure Cosmos Emulator Docker container ..."
    nohup bash ./run-docker-azure-cosmos-emulator-linux.sh &

build_script:
- sh: dotnet build -c Release

before_test:
- sh: |
    echo "Installing Azure Cosmos Emulator SSL certificate ..."
    sudo bash ./install-azure-cosmos-emulator-linux-certificates.sh

    if [ -f "./nohup.out" ]; then
        echo "--- BEGIN CONTENTS OF NOHUP.OUT ---"
        cat ./nohup.out
        echo "--- END CONTENTS OF NOHUP.OUT ---"
    fi

    bash ./print-environment-info.sh

test_script:
- pwsh: dotnet test --no-build -c Release -l "console;verbosity=detailed"
