image: Ubuntu

services:
- docker

before_build:
- sh: |
    # Start Azure Cosmos Emulator on Linux
    # Pull Azure Cosmos Emulator Docker image
    echo "Pulling Azure Cosmos Emulator Docker image for Linux ..."
    bash ./pull-docker-azure-cosmos-emulator-linux.sh

    # Start Azure Cosmos Emulator container
    echo "Running Azure Cosmos Emulator Docker container ..."
    nohup bash ./run-docker-azure-cosmos-emulator-linux.sh &

    # Wait for Docker container being started in the background
    echo "Waiting 60 seconds before trying to download Azure Cosmos Emulator SSL certificate ..."
    sleep 60

    # Print the background process output to see whether there are any errors
    if [ -f "./nohup.out" ]; then
        echo "--- BEGIN CONTENTS OF NOHUP.OUT ---"
        cat ./nohup.out
        echo "--- END CONTENTS OF NOHUP.OUT ---"
    fi

    # Install SSL certificate to be able to access the emulator
    echo "Installing Azure Cosmos Emulator SSL certificate ..."
    sudo bash ./install-azure-cosmos-emulator-linux-certificates.sh

build_script:
- sh: |
    echo "See whether the azure-cosmos-emulator-linux Docker container is running ..."
    docker ps --all

    echo "Verify that the container port 8081 is mapped correctly and accessible from an environment outside of the container ..."
    netstat -lt

    echo "Trying to access Azure Cosmos Emulator on localhost:8081 ..."
    curl -k https://localhost:8081/_explorer/emulator.pem
- pwsh: |
    Write-Output ".NET version:"
    dotnet --version

    Write-Output "Building and testing Release configuration ..."
    dotnet build -c Release
    dotnet test -c Release --no-build
